In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
corpus=pd.read_csv('/content/drive/MyDrive/DATASCIENCE/Dataset/amazonreviews.tsv',sep = '\t')

In [4]:
corpus.shape

(10000, 2)

In [5]:
corpus.head()

  label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [6]:
corpus.iloc[25]['review']

"Problem with charging smaller AAAs: I have had the charger for more than two years. It charges AA batteries just fine, but has a huge problem securing smaller AAA batteries. To charge the smaller batteries you need to flip down the little button at the positive end. In the beginning one of the four AAA batteries would pop up, and now three out of the four won't hold. The problem is the flip mechanism became loose, and any horizontal pressure would push the buttons back up. What I have to do now is using duct tape and a segment of crayon, apply the crayon on the buttons, and wrap the tape around. You know how painful that is."

In [7]:
corpus.iloc[25]['label']

'neg'

In [8]:
pip install vaderSentiment

Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from vaderSentiment) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2026.1.4)
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 3.6 MB/s eta 0:00:00
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

In [9]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [10]:
se=SentimentIntensityAnalyzer()

In [11]:
s='The movie was worst Movie i have ever seen'

In [12]:
se.polarity_scores(s)

{'neg': 0.339, 'neu': 0.661, 'pos': 0.0, 'compound': -0.6249}

In [13]:
s1='Wow I am very happy with the product, Loved it'
se.polarity_scores(s1)

{'neg': 0.0, 'neu': 0.374, 'pos': 0.626, 'compound': 0.9134}

In [14]:
corpus['Polarity_Score']=corpus['review'].apply(lambda x:se.polarity_scores(x))

In [15]:
corpus

,label,review,Polarity_Score
0,pos,Stuning even for the non-gamer: This sound tra...,"{'neg': 0.085, 'neu': 0.682, 'pos': 0.233, 'co..."
1,pos,The best soundtrack ever to anything.: I'm rea...,"{'neg': 0.017, 'neu': 0.846, 'pos': 0.137, 'co..."
2,pos,Amazing!: This soundtrack is my favorite music...,"{'neg': 0.062, 'neu': 0.674, 'pos': 0.264, 'co..."
3,pos,Excellent Soundtrack: I truly like this soundt...,"{'neg': 0.086, 'neu': 0.632, 'pos': 0.282, 'co..."
4,pos,"Remember, Pull Your Jaw Off The Floor After He...","{'neg': 0.0, 'neu': 0.72, 'pos': 0.28, 'compou..."
...,...,...,...
9995,pos,A revelation of life in small town America in ...,"{'neg': 0.017, 'neu': 0.852, 'pos': 0.132, 'co..."
9996,pos,Great biography of a very interesting journali...,"{'neg': 0.0, 'neu': 0.874, 'pos': 0.126, 'comp..."
9997,neg,Interesting Subject; Poor Presentation: You'd ...,"{'neg': 0.062, 'neu': 0.763, 'pos': 0.175, 'co..."
9998,neg,Don't buy: The box looked used and it is obvio...,"{'neg': 0.087, 'neu': 0.913, 'pos': 0.0, 'comp..."
9999,pos,Beautiful Pen and Fast Delivery.: The pen was ...,"{'neg': 0.027, 'neu': 0.821, 'pos': 0.152, 'co..."

In [16]:
corpus['compound']=corpus['Polarity_Score'].apply(lambda x:x['compound'])

In [17]:
corpus

,label,review,Polarity_Score,compound
0,pos,Stuning even for the non-gamer: This sound tra...,"{'neg': 0.085, 'neu': 0.682, 'pos': 0.233, 'co...",0.9454
1,pos,The best soundtrack ever to anything.: I'm rea...,"{'neg': 0.017, 'neu': 0.846, 'pos': 0.137, 'co...",0.8957
2,pos,Amazing!: This soundtrack is my favorite music...,"{'neg': 0.062, 'neu': 0.674, 'pos': 0.264, 'co...",0.9847
3,pos,Excellent Soundtrack: I truly like this soundt...,"{'neg': 0.086, 'neu': 0.632, 'pos': 0.282, 'co...",0.9814
4,pos,"Remember, Pull Your Jaw Off The Floor After He...","{'neg': 0.0, 'neu': 0.72, 'pos': 0.28, 'compou...",0.9840
...,...,...,...,...
9995,pos,A revelation of life in small town America in ...,"{'neg': 0.017, 'neu': 0.852, 'pos': 0.132, 'co...",0.9610
9996,pos,Great biography of a very interesting journali...,"{'neg': 0.0, 'neu': 0.874, 'pos': 0.126, 'comp...",0.9544
9997,neg,Interesting Subject; Poor Presentation: You'd ...,"{'neg': 0.062, 'neu': 0.763, 'pos': 0.175, 'co...",0.9467
9998,neg,Don't buy: The box looked used and it is obvio...,"{'neg': 0.087, 'neu': 0.913, 'pos': 0.0, 'comp...",-0.3595
9999,pos,Beautiful Pen and Fast Delivery.: The pen was ...,"{'neg': 0.027, 'neu': 0.821, 'pos': 0.152, 'co...",0.9107

In [18]:
corpus.iloc[10]['review']

"The Worst!: A complete waste of time. Typographical errors, poor grammar, and a totally pathetic plot add up to absolutely nothing. I'm embarrassed for this author and very disappointed I actually paid for this book."

In [19]:
age=45
print('You are eligible to vote') if(age>=18) else print('You are not eligible to vote')

You are eligible to vote

In [20]:
corpus['sentiment']=corpus['compound'].apply(lambda x:'pos' if x>=0 else 'neg')

In [21]:
corpus

,label,review,Polarity_Score,compound,sentiment
0,pos,Stuning even for the non-gamer: This sound tra...,"{'neg': 0.085, 'neu': 0.682, 'pos': 0.233, 'co...",0.9454,pos
1,pos,The best soundtrack ever to anything.: I'm rea...,"{'neg': 0.017, 'neu': 0.846, 'pos': 0.137, 'co...",0.8957,pos
2,pos,Amazing!: This soundtrack is my favorite music...,"{'neg': 0.062, 'neu': 0.674, 'pos': 0.264, 'co...",0.9847,pos
3,pos,Excellent Soundtrack: I truly like this soundt...,"{'neg': 0.086, 'neu': 0.632, 'pos': 0.282, 'co...",0.9814,pos
4,pos,"Remember, Pull Your Jaw Off The Floor After He...","{'neg': 0.0, 'neu': 0.72, 'pos': 0.28, 'compou...",0.9840,pos
...,...,...,...,...,...
9995,pos,A revelation of life in small town America in ...,"{'neg': 0.017, 'neu': 0.852, 'pos': 0.132, 'co...",0.9610,pos
9996,pos,Great biography of a very interesting journali...,"{'neg': 0.0, 'neu': 0.874, 'pos': 0.126, 'comp...",0.9544,pos
9997,neg,Interesting Subject; Poor Presentation: You'd ...,"{'neg': 0.062, 'neu': 0.763, 'pos': 0.175, 'co...",0.9467,pos
9998,neg,Don't buy: The box looked used and it is obvio...,"{'neg': 0.087, 'neu': 0.913, 'pos': 0.0, 'comp...",-0.3595,neg
9999,pos,Beautiful Pen and Fast Delivery.: The pen was ...,"{'neg': 0.027, 'neu': 0.821, 'pos': 0.152, 'co...",0.9107,pos

In [22]:
corpus['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [23]:
from sklearn.metrics import confusion_matrix,classification_report

In [24]:
y_true=corpus['label']
y_pred=corpus['sentiment']

In [25]:
confusion_matrix(y_true,y_pred)

array([[2630, 2467],
       [ 403, 4500]])

In [26]:
print(classification_report(y_true,y_pred))

              precision    recall  f1-score   support

         neg       0.87      0.52      0.65      5097
         pos       0.65      0.92      0.76      4903

    accuracy                           0.71     10000
   macro avg       0.76      0.72      0.70     10000
weighted avg       0.76      0.71      0.70     10000